source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MHExtendedMenuControl_Example', :exclusive => true do
  pod "MHExtendedMenuControl", :path => "../"
end

target 'MHExtendedMenuControl_Tests', :exclusive => true do
  pod "MHExtendedMenuControl", :path => "../"

  
end
